import { RouteInfo } from './immo-sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'Construire',
    iconType: 'material-icons-two-tone',
    icon: 'foundation',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: 'info-projet',
        title: 'Information du projet',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: 'estimation',
        title: 'Estimation',
        iconType: '',
        icon: 'calculate',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ]
  },
  {
    path: '',
    title: 'Assurer',
    iconType: 'material-icons-two-tone',
    icon: 'deck',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [ ],
  },
  {
    path: '',
    title: "S'informer",
    iconType: 'material-icons-two-tone',
    icon: '?',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [ ],
  },  

  // {
  //   path: 'info-projet',
  //   title: 'Information du projet',
  //   iconType: 'material-icons-two-tone',
  //   icon: 'home',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [ ],
  // },
  // {
  //     path: 'bien',
  //     title: 'Informations du Bien',
  //     iconType: 'material-icons-two-tone',
  //     icon: 'home',
  //     class: '',
  //     groupTitle: false,
  //     badge: '',
  //     badgeClass: '',
  //     submenu: [ ],
  //   },

  ];
